### ISSUE TITLE
QtNetwork incorrect parse HTTP headers

### ISSUE THREAD

**Issue by lubagov** [semlanik/qtprotobuf#228] opened 2021-06-13 20:33 UTC
Incorrect parsing of HTTP2 frame headers.

This happens when using Netty as the server HTTP2.0, the Java gRPC implementation server. Or with the `envoy` proxy server, in case use Qt only. The problem does not depend on the use of TLS and I can repeat it with or without encryption.

It seems Qt Network does not correctly parse the HTTP2.0 protocol frame headers. As result i can't use QtProtobuf and my gRPC server on Java.

```
qt.network.http2: connection error: SETTINGS invalid number of concurrent streams
qt.network.http2: stream 1 finished with error: "SETTINGS invalid number of concurrent streams"
QNetworkReply::ProtocolFailure "SETTINGS invalid number of concurrent streams"

```
I append code for reproduce, in QtProtobuf context, and in Qt.
[TestQtProtobuf.zip](https://github.com/semlanik/qtprotobuf/files/6644590/TestQtProtobuf.zip)
[TestQtHttp2.zip](https://github.com/semlanik/qtprotobuf/files/6644591/TestQtHttp2.zip)

I also create bugreport in Qt: https://bugreports.qt.io/browse/QTBUG-94470

Environment: Ubuntu 18.04, Qt 5.15.2 or 5.15.0.

maybe there is some bug-fix? I haven't been able to do it myself yet.

**Comment by semlanik** [comment] 2021-06-14 08:14
I guess it's a Qt issue, since you are able to reproduce it in pure Qt. And I'm afraid that Qt will fix it only in Qt6 for public use. I will check if there is workaround.

**Comment by lubagov** [comment] 2021-06-15 08:39
Seems yes, they fix it, in Qt6. And yes, it is really https://github.com/grpc/grpc-java/blob/c8ba60152958cb0f37d0e9a32ae406ce8d5f1ff0/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L103
Integer.MAX_VALUE here... And Netty has nothing to do with it, Netty if not redefine use 100 streams.

For myself, as I can control server, so I can fix it on server side:
```
ServerBuilder<?> builder=NettyServerBuilder
                                         .forPort(port,tlsBuilder.build())
                                         .maxConcurrentCallsPerConnection(1000);
```
Use, instance of:
```
ServerBuilder<?> builder=Grpc.newServerBuilderForPort(port,tlsBuilder.build()
```

**Comment by semlanik** [comment] 2021-06-15 08:49
Great, thanks for the investigation! I guess we may close this issue since you provided a workaround already.

**Closed by semlanik** 2021-06-15 08:49 UTC
Labels: bug, grpc
