### ISSUE TITLE
QML must be enabled to use QtProtoBuf?

### ISSUE THREAD

**Issue by Meneleus** [semlanik/qtprotobuf#239] opened 2021-08-21 15:36 UTC
I am getting a compile time error:
"Cannot open include file: 'QQmlEngine': No such file or directory"

On a project that does NOT have QML enabled. MUST I enable QML for QtProtoBuf to work?

Thank you

**Comment by semlanik** [comment] 2021-08-22 08:44
Hi @Meneleus , could you please describe an issue in a bit more detailed way? What file cause an issue? What arguments did you use to build QtProtobuf. If an error is displayed in your project, please provide a minimal sample that reproduces an issue. Thanks!

**Comment by Meneleus** [comment] 2021-08-23 14:05
I used the ZIP version and setup a project with a simple proto file. Generated code with:

```
protoc --plugin=protoc-gen-qtprotobuf=..\bin\qtprotobufgen.exe --qtprotobuf_out=generated -I. project.proto
```

Then linking in the code with Qt I get: `Cannot open include file: 'QQmlExtensionPlugin': No such file or directory.

Isn't this (in qtprotobufglobal.h) backwards:
```
#ifndef Q_PROTOBUF_IMPORT_QUICK_PLUGIN
```

Shouldn't that be #ifdef?

**Comment by Meneleus** [comment] 2021-08-23 14:06
Everywhere else I get:
```
Cannot open include file: 'QQmlEngine': No such file or directory
```

This is because `qprotobuflazymessagepointer.h` #includes <QQmlEngine>.

**Comment by semlanik** [comment] 2021-08-23 14:22
> I used the ZIP version and setup a project with a simple proto file. Generated code with:
> 
> ```
> protoc --plugin=protoc-gen-qtprotobuf=..\bin\qtprotobufgen.exe --qtprotobuf_out=generated -I. project.proto
> ```
> 
> Then linking in the code with Qt I get: `Cannot open include file: 'QQmlExtensionPlugin': No such file or directory.
> 
> Isn't this (in qtprotobufglobal.h) backwards:
> 
> ```
> #ifndef Q_PROTOBUF_IMPORT_QUICK_PLUGIN
> ```
> 
> Shouldn't that be #ifdef?

I don't think that it should be fixed this way, because it's only protection of macro redefinition, but it seems you're right need to protect:
```cpp
    #ifdef QT_PROTOBUF_STATIC
        #include <QtPlugin>
        #include <QQmlExtensionPlugin>
        #define Q_PROTOBUF_IMPORT_QUICK_PLUGIN() \
            Q_IMPORT_PLUGIN(QtProtobufQuickPlugin) \
            qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QtProtobufQuickPlugin().instance())->registerTypes("QtProtobuf");
    #else
```
with an extra condition. qprotobuflazymessagepointer.h requires conditional build using the same flag as well, obviously.

If you already remember the name of macro that is used to detect QtQuick in a build, you are welcome to submit a patchset, otherwise, I will check this in the evening.

Thanks!

**Closed** 2021-09-14 08:24 UTC
Labels: bug, protobuf
